#!/bin/bash

# set explanation: https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
# set -euxo pipefail # print executed commands to the terminal
set -euo pipefail # don't print executed commands to the terminal

# explanation of ANSI escape sequences for the Select Graphic Rendition subset
# https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences
echo -e "\033[31;42mrepository pre-exit hook here, hai! 👋\033[0m"

# bold (1) doesn't work
# faint (2) just looks gray 
# rapid-blink (6) is the same as slow-blink (5)
# conceal (8) doesn't work
# background colors 43-47 don't work
# background colors 100-107 don't work

# so we're left with...
# 3 italic
# 4 underline
# 5 slow-blink
# 9 crossed-out
# 30-37 foreground colors
# 40-47 background colors

echo -e ""
echo -e "We can use 16 different foreground colors..."
echo -e "\033[30;41m   01. black (FG30) on red (BG41)   \033[0m"
echo -e "\033[31;42m   02. red (FG31) on green (BG42)   \033[0m"
echo -e "\033[32;43m   03. green (FG32) on yellow (BG43)   \033[0m"
echo -e "\033[33;44m   04. yellow (FG33) on blue (BG44)   \033[0m"
echo -e "\033[34;45m   05. blue (FG34) on magenta (BG45)   \033[0m"
echo -e "\033[35;46m   06. magenta (FG35) on cyan (BG46)   \033[0m"
echo -e "\033[36;47m   07. cyan (FG36) on white (BG47)   \033[0m"
echo -e "\033[37;40m   08. white (FG37) on black (BG40)   \033[0m"
echo -e "\033[90;101m   09. bright black (FG90) on bright red (BG101)   \033[0m"
echo -e "\033[91;102m   10. bright red (FG91) on bright green (BG102)  \033[0m"
echo -e "\033[92;103m   11. bright green (FG92) on bright yellow (BG103)  \033[0m"
echo -e "\033[93;104m   12. bright yellow (FG93) on bright blue (BG104)   \033[0m"
echo -e "\033[94;105m   13. bright blue (FG94) on bright magenta (BG105)  \033[0m"
echo -e "\033[95;106m   14. bright magenta (FG95) on bright cyan (BG106)  \033[0m"
echo -e "\033[96;107m   15. bright cyan (FG96) on bright white (BG107)  \033[0m"
echo -e "\033[97;100m   16. bright white (FG97) on bright black (BG108)  \033[0m"
echo -e ""
echo -e "We can use 3 different background colors..."
echo -e "\033[40m   01. black (BG40)   \033[0m"
echo -e "\033[41m   02. red (BG41)   \033[0m"
echo -e "\033[42m   03. green (BG42)   \033[0m"
echo -e ""
echo -e "We can use text styling..."
echo -e "\033[3m   this is italic text   \033[0m"
echo -e "\033[4m   this is underlined text   \033[0m"
echo -e "\033[5m   this is blinking text   \033[0m"
echo -e "\033[9m   this striked text   \033[0m"
echo -e ""
echo -e "We can use emojis..."
echo -e "\033[:thisisfine::perfection::bash::sadpanda::partyparrot::docker::metal::red_button: 👋\033[0m"
echo -e ":thisisfine::perfection::bash::sadpanda::partyparrot::docker::metal::red_button:"
echo -e ":cow::bell:"
echo -e "--- Running \033[33mspecs\033[0m :cow::bell:"
echo -e "Running \033[33mspecs\033[0m :cow::bell:"
# :terminal:
# :speech_balloon:
# :ghost:
# :writing_hand:
# :index_pointing_at_the_viewer:
# :brain:
# :mage:
# :astronaut:
# :scientist:
# :technologist:
# :teacher:
# :artist:
# :cook:
# :supervillain:
# :superhero:
# :ninja:
# :juggling:
# :shrug:
# :pinched_fingers:
# :nail_care:

echo -e ""
echo -e "And we can do any combination of the above..."

# 3 italic
# 4 underline
# 5 slow-blink
# 9 crossed-out

echo -e "\033[31;42mrepository pre-exit hook here, hai! 👋\033[0m"


echo -e "\033[33;6;44mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;3;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[35;9;46mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[36;21;41mrepository pre-exit hook here, hai! 👋\033[0m"

echo -e "\033[34;51;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;52;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;53;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;3;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e ""
echo -e "\033[31;1;4mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[38;5;206;48;5;57mrepository pre-exit hook here, hai! 👋\033[0m"


# Job lifecycle hooks have access to all the standard Buildkite environment variables.
echo -e "\033[31;1;4mJob lifecycle hooks have access to all the standard Buildkite environment variables...\033[0m"
echo "BUILDKITE_PIPELINE_SLUG=$BUILDKITE_PIPELINE_SLUG"
echo "CI=$CI"
echo "BUILDKITE=$BUILDKITE"
echo "BUILDKITE_ORGANIZATION_SLUG=$BUILDKITE_ORGANIZATION_SLUG"
echo "BUILDKITE_PIPELINE_SLUG=$BUILDKITE_PIPELINE_SLUG"
echo "BUILDKITE_PIPELINE_NAME=$BUILDKITE_PIPELINE_NAME"
echo "BUILDKITE_PIPELINE_ID=$BUILDKITE_PIPELINE_ID"
echo "BUILDKITE_PIPELINE_PROVIDER=$BUILDKITE_PIPELINE_PROVIDER"
echo "BUILDKITE_PIPELINE_DEFAULT_BRANCH=$BUILDKITE_PIPELINE_DEFAULT_BRANCH"
echo "BUILDKITE_REPO=$BUILDKITE_REPO"
echo "BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID"
echo "BUILDKITE_BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER"
echo "BUILDKITE_BUILD_URL=$BUILDKITE_BUILD_URL"
echo "BUILDKITE_BRANCH=$BUILDKITE_BRANCH"
echo "BUILDKITE_TAG=$BUILDKITE_TAG"
echo "BUILDKITE_COMMIT=$BUILDKITE_COMMIT"
echo "BUILDKITE_MESSAGE=$BUILDKITE_MESSAGE"
echo "BUILDKITE_SOURCE=$BUILDKITE_SOURCE"
echo "BUILDKITE_BUILD_AUTHOR=$BUILDKITE_BUILD_AUTHOR"
echo "BUILDKITE_BUILD_AUTHOR_EMAIL=$BUILDKITE_BUILD_AUTHOR_EMAIL"
echo "BUILDKITE_BUILD_CREATOR=$BUILDKITE_BUILD_CREATOR"
echo "BUILDKITE_BUILD_CREATOR_EMAIL=$BUILDKITE_BUILD_CREATOR_EMAIL"
echo "BUILDKITE_REBUILT_FROM_BUILD_ID=$BUILDKITE_REBUILT_FROM_BUILD_ID"
echo "BUILDKITE_REBUILT_FROM_BUILD_NUMBER=$BUILDKITE_REBUILT_FROM_BUILD_NUMBER"
echo "BUILDKITE_PULL_REQUEST=$BUILDKITE_PULL_REQUEST"
echo "BUILDKITE_PULL_REQUEST_BASE_BRANCH=$BUILDKITE_PULL_REQUEST_BASE_BRANCH"
echo "BUILDKITE_PULL_REQUEST_REPO=$BUILDKITE_PULL_REQUEST_REPO"
echo "BUILDKITE_TRIGGERED_FROM_BUILD_ID=$BUILDKITE_TRIGGERED_FROM_BUILD_ID"
echo "BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER=$BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER"
echo "BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG=$BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG"
echo "BUILDKITE_JOB_ID=$BUILDKITE_JOB_ID"
echo "BUILDKITE_LABEL=$BUILDKITE_LABEL"
echo "BUILDKITE_COMMAND=$BUILDKITE_COMMAND"
echo "BUILDKITE_ARTIFACT_PATHS=$BUILDKITE_ARTIFACT_PATHS"
echo "BUILDKITE_RETRY_COUNT=$BUILDKITE_RETRY_COUNT"
echo "BUILDKITE_TIMEOUT=$BUILDKITE_TIMEOUT"
echo "BUILDKITE_STEP_KEY=$BUILDKITE_STEP_KEY"
echo "BUILDKITE_STEP_ID=$BUILDKITE_STEP_ID"
echo "BUILDKITE_PROJECT_SLUG=$BUILDKITE_PROJECT_SLUG"
echo "BUILDKITE_PROJECT_PROVIDER=$BUILDKITE_PROJECT_PROVIDER"
echo "BUILDKITE_SCRIPT_PATH=$BUILDKITE_SCRIPT_PATH"
echo "BUILDKITE_AGENT_ID=$BUILDKITE_AGENT_ID"
echo "BUILDKITE_AGENT_NAME=$BUILDKITE_AGENT_NAME"
echo "BUILDKITE_AGENT_META_DATA_QUEUE=$BUILDKITE_AGENT_META_DATA_QUEUE"
echo "BUILDKITE_AGENT_META_DATA_DOCKER=$BUILDKITE_AGENT_META_DATA_DOCKER"
echo "BUILDKITE_AGENT_META_DATA_STACK=$BUILDKITE_AGENT_META_DATA_STACK"
echo "BUILDKITE_AGENT_META_DATA_BUILDKITE_AWS_STACK=$BUILDKITE_AGENT_META_DATA_BUILDKITE_AWS_STACK"
echo "BUILDKITE_AGENT_META_DATA_AWS_AVAILABILITY_ZONE=$BUILDKITE_AGENT_META_DATA_AWS_AVAILABILITY_ZONE"
echo "BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_ID=$BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_ID"
echo "BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE=$BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE"
echo "BUILDKITE_AGENT_META_DATA_AWS_REGION=$BUILDKITE_AGENT_META_DATA_AWS_REGION"
echo "BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_LIFE_CYCLE=$BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_LIFE_CYCLE"
echo "BUILDKITE_AGENT_META_DATA_AWS_ACCOUNT_ID=$BUILDKITE_AGENT_META_DATA_AWS_ACCOUNT_ID"
echo "BUILDKITE_AGENT_META_DATA_AWS_AMI_ID=$BUILDKITE_AGENT_META_DATA_AWS_AMI_ID"
echo "BUILDKITE_AGENT_META_DATA_AWS_ARCHITECTURE=$BUILDKITE_AGENT_META_DATA_AWS_ARCHITECTURE"
echo "BUILDKITE_PIPELINE_TEAMS=$BUILDKITE_PIPELINE_TEAMS"
echo "BUILDKITE_BUILD_CREATOR_TEAMS=$BUILDKITE_BUILD_CREATOR_TEAMS"


# https://buildkite.com/docs/pipelines/managing-log-output#redacted-environment-variables
# These variables will be redacted from logs....

MY_PASSWORD="ThisIsASecret"
MY_SECRET="ThisIsASecret"
MY_TOKEN="ThisIsASecret"
MY_ACCESS_KEY="ThisIsASecret"
MY_SECRET_KEY="ThisIsASecret"
MY_CONNECTION_STRING="ThisIsASecret" # (added in Agent v3.53.0)

echo "MY_PASSWORD=$MY_PASSWORD"
echo "MY_SECRET=$MY_SECRET"
echo "MY_TOKEN=$MY_TOKEN"
echo "MY_ACCESS_KEY=$MY_ACCESS_KEY"
echo "MY_SECRET_KEY=$MY_SECRET_KEY"
echo "MY_CONNECTION_STRING=$MY_CONNECTION_STRING"
