#!/bin/bash

# set explanation: https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
# set -euxo pipefail # print executed commands to the terminal
set -euo pipefail # don't print executed commands to the terminal

# explanation of ANSI escape sequences for the Select Graphic Rendition subset
# https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences
echo -e "\033[31;42mrepository pre-exit hook here, hai! 👋\033[0m"


# bold (1) doesn't work
# faint (2) just looks gray 
# rapid-blink (6) is the same as slow-blink (5)
# conceal (8) doesn't work
# background colors 

# so we're left with...
# 1 bold
# 3 italic
# 4 underline
# 5 slow-blink
# 9 crossed-out
# 30-37 foreground colors
# 40-47 background colors

echo -e "We can use 16 different foreground colors..."
echo -e "\033[30;41m   01. black on red   \033[0m"
echo -e "\033[31;42m   02. red on green   \033[0m"
echo -e "\033[32;43m   03. green on yellow   \033[0m"
echo -e "\033[33;44m   04. yellow on blue   \033[0m"
echo -e "\033[34;45m   05. blue on magenta   \033[0m"
echo -e "\033[35;46m   06. magenta on cyan   \033[0m"
echo -e "\033[36;47m   07. cyan on white   \033[0m"
echo -e "\033[37;40m   08. white on black   \033[0m"
echo -e "\033[90;101m  09. bright black   \033[0m"
echo -e "\033[91;102m  10. bright red   \033[0m"
echo -e "\033[92;103m  11. bright green   \033[0m"
echo -e "\033[93;104m  12. bright yellow   \033[0m"
echo -e "\033[94;105m  13. bright blue   \033[0m"
echo -e "\033[95;106m  14. bright magenta   \033[0m"
echo -e "\033[96;107m  15. bright cyan   \033[0m"
echo -e "\033[97;100m  16. bright white   \033[0m"





echo -e "\033[31;42mrepository pre-exit hook here, hai! 👋\033[0m"


echo -e "\033[33;6;44mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;3;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[35;9;46mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[36;21;41mrepository pre-exit hook here, hai! 👋\033[0m"

echo -e "\033[34;51;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;52;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;53;45mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[34;3;45mrepository pre-exit hook here, hai! 👋\033[0m"

echo -e "\033[31;1;4mrepository pre-exit hook here, hai! 👋\033[0m"
echo -e "\033[38;5;206;48;5;57mrepository pre-exit hook here, hai! 👋\033[0m"


# Job lifecycle hooks have access to all the standard Buildkite environment variables.
echo -e "\033[31;1;4mJob lifecycle hooks have access to all the standard Buildkite environment variables...\033[0m"
echo "BUILDKITE_PIPELINE_SLUG=$BUILDKITE_PIPELINE_SLUG"
echo "CI=$CI"
echo "BUILDKITE=$BUILDKITE"
echo "BUILDKITE_ORGANIZATION_SLUG=$BUILDKITE_ORGANIZATION_SLUG"
echo "BUILDKITE_PIPELINE_SLUG=$BUILDKITE_PIPELINE_SLUG"
echo "BUILDKITE_PIPELINE_NAME=$BUILDKITE_PIPELINE_NAME"
echo "BUILDKITE_PIPELINE_ID=$BUILDKITE_PIPELINE_ID"
echo "BUILDKITE_PIPELINE_PROVIDER=$BUILDKITE_PIPELINE_PROVIDER"
echo "BUILDKITE_PIPELINE_DEFAULT_BRANCH=$BUILDKITE_PIPELINE_DEFAULT_BRANCH"
echo "BUILDKITE_REPO=$BUILDKITE_REPO"
echo "BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID"
echo "BUILDKITE_BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER"
echo "BUILDKITE_BUILD_URL=$BUILDKITE_BUILD_URL"
echo "BUILDKITE_BRANCH=$BUILDKITE_BRANCH"
echo "BUILDKITE_TAG=$BUILDKITE_TAG"
echo "BUILDKITE_COMMIT=$BUILDKITE_COMMIT"
echo "BUILDKITE_MESSAGE=$BUILDKITE_MESSAGE"
echo "BUILDKITE_SOURCE=$BUILDKITE_SOURCE"
echo "BUILDKITE_BUILD_AUTHOR=$BUILDKITE_BUILD_AUTHOR"
echo "BUILDKITE_BUILD_AUTHOR_EMAIL=$BUILDKITE_BUILD_AUTHOR_EMAIL"
echo "BUILDKITE_BUILD_CREATOR=$BUILDKITE_BUILD_CREATOR"
echo "BUILDKITE_BUILD_CREATOR_EMAIL=$BUILDKITE_BUILD_CREATOR_EMAIL"
echo "BUILDKITE_REBUILT_FROM_BUILD_ID=$BUILDKITE_REBUILT_FROM_BUILD_ID"
echo "BUILDKITE_REBUILT_FROM_BUILD_NUMBER=$BUILDKITE_REBUILT_FROM_BUILD_NUMBER"
echo "BUILDKITE_PULL_REQUEST=$BUILDKITE_PULL_REQUEST"
echo "BUILDKITE_PULL_REQUEST_BASE_BRANCH=$BUILDKITE_PULL_REQUEST_BASE_BRANCH"
echo "BUILDKITE_PULL_REQUEST_REPO=$BUILDKITE_PULL_REQUEST_REPO"
echo "BUILDKITE_TRIGGERED_FROM_BUILD_ID=$BUILDKITE_TRIGGERED_FROM_BUILD_ID"
echo "BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER=$BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER"
echo "BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG=$BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG"
echo "BUILDKITE_JOB_ID=$BUILDKITE_JOB_ID"
echo "BUILDKITE_LABEL=$BUILDKITE_LABEL"
echo "BUILDKITE_COMMAND=$BUILDKITE_COMMAND"
echo "BUILDKITE_ARTIFACT_PATHS=$BUILDKITE_ARTIFACT_PATHS"
echo "BUILDKITE_RETRY_COUNT=$BUILDKITE_RETRY_COUNT"
echo "BUILDKITE_TIMEOUT=$BUILDKITE_TIMEOUT"
echo "BUILDKITE_STEP_KEY=$BUILDKITE_STEP_KEY"
echo "BUILDKITE_STEP_ID=$BUILDKITE_STEP_ID"
echo "BUILDKITE_PROJECT_SLUG=$BUILDKITE_PROJECT_SLUG"
echo "BUILDKITE_PROJECT_PROVIDER=$BUILDKITE_PROJECT_PROVIDER"
echo "BUILDKITE_SCRIPT_PATH=$BUILDKITE_SCRIPT_PATH"
echo "BUILDKITE_AGENT_ID=$BUILDKITE_AGENT_ID"
echo "BUILDKITE_AGENT_NAME=$BUILDKITE_AGENT_NAME"
echo "BUILDKITE_AGENT_META_DATA_QUEUE=$BUILDKITE_AGENT_META_DATA_QUEUE"
echo "BUILDKITE_AGENT_META_DATA_DOCKER=$BUILDKITE_AGENT_META_DATA_DOCKER"
echo "BUILDKITE_AGENT_META_DATA_STACK=$BUILDKITE_AGENT_META_DATA_STACK"
echo "BUILDKITE_AGENT_META_DATA_BUILDKITE_AWS_STACK=$BUILDKITE_AGENT_META_DATA_BUILDKITE_AWS_STACK"
echo "BUILDKITE_AGENT_META_DATA_AWS_AVAILABILITY_ZONE=$BUILDKITE_AGENT_META_DATA_AWS_AVAILABILITY_ZONE"
echo "BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_ID=$BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_ID"
echo "BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE=$BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE"
echo "BUILDKITE_AGENT_META_DATA_AWS_REGION=$BUILDKITE_AGENT_META_DATA_AWS_REGION"
echo "BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_LIFE_CYCLE=$BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_LIFE_CYCLE"
echo "BUILDKITE_AGENT_META_DATA_AWS_ACCOUNT_ID=$BUILDKITE_AGENT_META_DATA_AWS_ACCOUNT_ID"
echo "BUILDKITE_AGENT_META_DATA_AWS_AMI_ID=$BUILDKITE_AGENT_META_DATA_AWS_AMI_ID"
echo "BUILDKITE_AGENT_META_DATA_AWS_ARCHITECTURE=$BUILDKITE_AGENT_META_DATA_AWS_ARCHITECTURE"
echo "BUILDKITE_PIPELINE_TEAMS=$BUILDKITE_PIPELINE_TEAMS"
echo "BUILDKITE_BUILD_CREATOR_TEAMS=$BUILDKITE_BUILD_CREATOR_TEAMS"


# https://buildkite.com/docs/pipelines/managing-log-output#redacted-environment-variables
# These variables will be redacted from logs....

MY_PASSWORD="ThisIsASecret"
MY_SECRET="ThisIsASecret"
MY_TOKEN="ThisIsASecret"
MY_ACCESS_KEY="ThisIsASecret"
MY_SECRET_KEY="ThisIsASecret"
MY_CONNECTION_STRING="ThisIsASecret" # (added in Agent v3.53.0)

echo "MY_PASSWORD=$MY_PASSWORD"
echo "MY_SECRET=$MY_SECRET"
echo "MY_TOKEN=$MY_TOKEN"
echo "MY_ACCESS_KEY=$MY_ACCESS_KEY"
echo "MY_SECRET_KEY=$MY_SECRET_KEY"
echo "MY_CONNECTION_STRING=$MY_CONNECTION_STRING"
